import Header from "@/components/Header";
import "./globals.css";
import { PT_Serif } from "next/font/google";
import Footer from "@/components/Footer";
import { AuthContextProvider } from "@/context/AuthContext";

const inter = PT_Serif({ weight: "400", subsets: ["latin"] });

export const metadata = {
	title: "Elox App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AuthContextProvider>
					<Header />
					{children}
					<Footer />
				</AuthContextProvider>
			</body>
		</html>
	);
}
